name: train and predict

on:
  push:
    branches:
      - docker_ci

jobs:

  train_model:
    name: Train Scikit-learn Model
    runs-on: ubuntu-latest 

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip # Upgrades pip for best practice
          pip install -r requirements.txt # Installs all libraries needed by train.py

      - name: Run training script to generate model
        run: python src/train.py #

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model 
          path: model/ 
          retention-days: 15

 
  docker_operations:
    name: Build, Test & Push Docker Image
    runs-on: ubuntu-latest 
    needs: train_model 

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download trained model artifact
        uses: actions/download-artifact@v3 
        with:
          name: trained-model
          path: model/ 

      - name: Build Docker image
        run: |
          docker build -t my-image-name . 

      - name: Run Docker container with predict.py for verification
        run: |
          docker run --rm my-image-name python src/predict.py

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Push Docker image to DockerHub
        run: |
          docker tag my-image-name ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:latest